### ISSUE TITLE
Cross Origin Ressource Sharing

### ISSUE THREAD

**Issue by IrisTheSnail** [Gh-Badr/HarmoniAPI#1]
Hello there!
I can't access the back as the CORS setting stops me.
![image](https://github.com/Gh-Badr/HarmoniAPI/assets/91791764/5b708d57-daf0-4c93-aae4-5bd0e876c802)

**Comment by Gh-Badr** [comment]
This problem happens when two apps running on the same host try to communicate with each other through HTTP requests. 

This link explains how to solve this issue : https://www.angularjswiki.com/angular/origin-http-localhost4200-has-been-blocked-by-cors-policy-in-angular-error/
